use_frameworks!

target 'MakemojiSDK-iMessageExtension_Example' do
  pod 'MakemojiSDK-iMessageExtension', :path => '../'

  target 'MakemojiSDK-iMessageExtension_Tests' do
    inherit! :search_paths

    
  end
end
